export const archetypes = [
    { 
        name: "Pathfinder",
        slug: "pathfinder",
        icon: "/archetypes/pathfinder-symbol.png",
        song: "/archetypes/songs/pathfinder.mp3",
        description: "Walks where the trail has vanished. Trusts the unknown. Loses the clear path.  That’s how the truth is found.",
        tagline: "walk beyond the edge of the map",
        base: [
            "You’ve always felt it—that soft pull on your heart, like wind through tall grass, calling you toward something just out of sight.  Not for the thrill of the unknown, but for the truth it hides.  You walk roads others don’t notice, speaking quietly to rivers and rustling leaves, asking questions with your feet.",
            "The world does not always understand your restlessness.  But you were not made to stay still.  You are the mapmaker of your own soul, and each step you take is a vow to never stop listening."
        ],
        shadowTag: "sometimes the wind calls not to freedom, but to escape.",
        shadowText: "Even the most courageous souls sometimes wander not toward truth, but away from pain. These are soft signs that The Pathfinder may be seeking distance instead of depth:",
        shadowList: [
            "You keep moving but feel no closer to peace.",
            "The idea of staying — in one place, with one person, in one truth — brings quiet dread.",
            "You fear being known, because you’ve learned that to be still is to be seen.",
            "You chase new paths not from wonder, but from a quiet ache you cannot name.",
        ],
        reframeTag: "this ache was never your flaw, it was your invitation...",
        reframeText: "What you call restlessness may be a deep longing for belonging.  Not to a place or a person—but to yourself.  Your instinct to move is not wrong.  But sometimes the real wilderness waits inside.  You are not lost in the stillness.  You are simply remembering how to be guided without a map.",
        gratitudeThanks: "Thank You, Pathfinder",
        gratitudeIntro: [
            "Find a quiet moment—perhaps with soft light or near an open window—and breathe.",
            "Close your eyes.  Feel the part of you that listens for the horizon, even in the quiet when others sleep.  The one who said yes to the unknown when it would’ve been easier to stay.",
        ],
        affirmationIntro: "Speak inwardly, or whisper aloud:",
        affirmation: [
            '"Thank you, Pathfinder.  For never letting me grow numb.',
            'For choosing movement over comfort, questions over quiet.',
            'For walking with me—even when I did not know where we were going."',
        ],
        affirmationSettle: "Place a hand over your chest or heart. You’ve made it this far. That matters.",
        reflectionTag: "Where am I truly being called—and where am I simply afraid to stay?",
        reflectionSettle: "Let the question rest inside you like a pebble in a river. You do not need to answer right away. Just feel where it ripples.",
        partingMessage: "The horizon will wait.  For now, rest your feet, and trust that the road will remember you when you’re ready to walk again."
    },
    { 
        name: 'Orphan',
        slug: "orphan",
        icon: '/archetypes/orphan-symbol.png',
        song: '/archetypes/songs/orphan.mp3',
        description: "Knows the ache of being outside. Carries longing like a lantern. Trust builds slowly, but the heart is fierce.",
        tagline: "come home to the place you’ve always been.",
        base: [
            "You have known absence, the kind that echoes.  Not just of people, but of safety, of certainty.  Yet it is in that ache you found your deepest strength.  While others built walls, you built lanterns—small lights to carry through the dark.  You do not need to pretend.",
            "You are not broken.  You are the survivor of a thousand quiet storms, and still, your heart opens.  Still, you hope.  And in that hope, you have already begun to come home."
        ],
        shadowTag: "signs the Orphan may be protecting you from wounds too long carried.",
        shadowList: [
            "You find yourself expecting abandonment, even in safe places.",
            'You carry a quiet ache that whispers, “Don’t get too close.”',
            "You feel invisible in groups, unsure if you belong anywhere at all.",
            "You sometimes offer comfort to others while silently wishing someone would notice your own pain.",
        ],
        reframeTag: "being left out wasn’t your wound, it was your awakening...",
        reframeText: "These aren’t flaws—they are the echoes of long-unseen grief. The Orphan in you is not weak, but wise.  It learned to survive when no one came, and still it dares to believe in light.  This ache is not your identity, it’s a doorway home.",
        gratitudeThanks: "Thank You, Tender Guardian",
        gratitudeIntro: [
            "Take a deep breath.  Place a gentle hand over your heart.  Imagine the younger version of yourself, the one who waited, who hoped, who hurt.",
            "Picture them not as fragile, but as resilient. Brave in their softness.",
        ],
        affirmationIntro: "Now, whisper silently or aloud:",
        affirmation: [
            '"Thank you for keeping me safe when no one else could.',
            'Thank you for carrying the ache with such grace.',
            'I see you now. And I won’t abandon you."'
        ],
        affirmationSettle: "Let this moment settle like rain on dry soil.",
        reflectionTag: "Where in my life have I mistaken protection for isolation?",
        reflectionSettle: "Let the ache soften in your chest like breath through a cracked window. You do not need to reach for the answer. Just let it find you when it’s ready.",
        partingMessage: "Even if the world forgets, this place remembers you.  The light is still in your hands.  Come home whenever you need.",
    },
    { 
        name: 'Hero',
        slug: 'hero',
        icon: '/archetypes/hero-symbol.png',
        song: '/archetypes/songs/hero.mp3',
        description: "Stands when others turn away.  Bleeds for the cause.  The struggle isn’t a burden, it’s the proving ground.",
        tagline: "let your courage follow your heart.",
        base: [
            'You carry storms in your chest and sunlight in your hands.  Not because you seek glory, but because you cannot bear to leave things undone.  You fight not to conquer, but to protect what matters most: love, truth, the quiet dignity of trying.',
            'There is tenderness in your fire, a discipline that grows from knowing pain and still choosing to rise.  You are not defined by the battles, but by the reasons you pick up the sword.',
        ],
        shadowTag: 'when the fight to protect becomes a fight to prove.',
        shadowList: [
            "You take on burdens that aren’t yours because it feels wrong to say no.",
            "You feel guilty resting, as if you're only valuable when you're helping.",
            "You hide your own pain so others won’t worry or think you’re weak.",
            "You sometimes chase battles just to feel needed or worthy.",
        ],
        reframeTag: 'the struggle was never to break you, but to forge you...',
        reframeText: 'These aren’t failures, they’re the traces of someone who learned that love is earned through effort.  But your worth is not in what you do, it’s in who you are, even in stillness.  The Hero doesn’t need to win every war.  Sometimes, their greatest act of courage ...is learning to lay down the sword.',
        gratitudeThanks: 'Thank You, Brave Heart',
        gratitudeIntro: [
            'Close your eyes.  Feel the weight of all the battles you’ve fought.  Some were visible, many were not.',
            'Imagine placing each one gently beside you, like old armour removed with care.',
        ],
        affirmationIntro: "Now, whisper silently or aloud:",
        affirmation: [
            '"Thank you for fighting when I felt too small.',
            'Thank you for standing tall when I wanted to run.',
            'I honour your strength and I give you permission to rest."',
        ],
        affirmationSettle: 'Breathe deeply into the space left behind.',
        reflectionTag: 'If I no longer had to prove anything, what would I choose to protect today?',
        reflectionSettle: 'Let the question fall like ash from a long battle.  You do not need to act, just rest in what it stirs.',
        partingMessage: "You’ve done enough for today.  Let your heart rest its armour.  The world will call again—but not tonight.",
    },
    { 
        name: 'Lover',
        slug: 'lover',
        icon: '/archetypes/lover-symbol.png',
        song: '/archetypes/songs/lover.mp3',
        description: "Feels with wild honesty. Sees beauty others miss. Chooses love not as weakness, but as devotion.",
        tagline: 'love with your whole being, no matter the cost.',
        base: [
            'To be you is to feel in colours others haven’t named yet.  You carry beauty in your touch, connection in your gaze, tenderness in every breath.  You don’t just love people, you love mornings, music, the way rain sounds against old windows.  You are intimacy incarnate.',
            'Your strength is not softness alone, but the bravery it takes to stay open in a world that numbs.  You remind others that they are lovable as they are.  You remind yourself too, again and again.  In a world starved of depth, you are a deep, clear well.',
        ],
        shadowTag: 'when love becomes longing, and connection turns into self-forgetting.',
        shadowList: [
            'You give too much, even when you’re empty.',
            'You fear being alone, and so you stay—too long, too quietly.',
            'You lose yourself in others’ needs, forgetting your own reflection.',
            'You crave intensity, and sometimes mistake chaos for passion.'
        ],
        reframeTag: 'longing was never your weakness — it was your way home.',
        reframeText: 'You love with a holy kind of heart, but you are not made to pour endlessly without being filled.  Love is not only what you give, it’s also what you allow yourself to receive.  Even when your hands are empty, your presence is enough.  You are already worthy of the depth you seek.',
        gratitudeThanks: 'Thank You, Open Heart',
        gratitudeIntro: [
            'Close your eyes and place both hands over your heart.',
        ],
        affirmationIntro: 'Say softly:',
        affirmation: [
            '"Thank you for the way I feel.',
            'For the warmth I bring into the world.',
            'I honour the depth in me that longs and still chooses to stay soft."'
        ],
        affirmationSettle: 'Breathe in slowly.  Feel the warmth in your chest—not reaching outward, but glowing just for you.',
        reflectionTag: 'Where in my life might I love myself as deeply as I love others?',
        reflectionSettle: 'Let the ache soften like candlelight on skin. You don’t need to chase the feeling — just let it stay a moment longer.',
        partingMessage: "Carry the warmth with you.  Let every touch be slower, every breath more whole.  You have already loved enough for one day.",
    },
    { 
        name: 'Rebel',
        slug: 'rebel',
        icon: '/archetypes/rebel-symbol.png',
        song: '/archetypes/songs/rebel.mp3',
        description: "Refuses the false.  Burns the rulebook.  This fire isn’t anger, it’s loyalty to something truer.",
        tagline: 'break what binds you, gently.',
        base: [
            'You are not chaos—you are clarity dressed in flame.  While others cling to what crumbles, you see the beauty in letting go.  You don’t destroy for destruction’s sake.  You tear down illusions, burn hollow structures, and speak the truths no one dares to whisper.  And in the ash, you plant seeds.',
            'It is not easy to be you.  People fear what you reveal.  But you do not come to wound, you come to free.  You are the necessary ending, the sacred storm, the voice that says, “This is not who I am anymore”.  And in that rupture, life begins again.',
        ],
        shadowTag: 'when your truth scorches before it softens.',
        shadowList: [
            'You feel compelled to leave situations before they leave you, burning bridges that once held love.',
            'You carry a quiet anger, often unspoken, at systems, people, or yourself.',
            'You find it hard to sit still in peace, as if something always needs tearing down to prove you’re awake.',
            'You fear becoming stagnant more than you fear becoming alone.',
        ],
        reframeTag: "your fire was never to destroy, it was to reveal what still lives beneath the ash.",
        reframeText: "You were never here to be gentle for comfort's sake — you were born to be honest for freedom's.  But not all truth needs a blaze.  Sometimes, the deepest revolutions begin with a whisper.  You can choose which fires to light.  You can walk away without turning everything to ash.",
        gratitudeThanks: 'Thank You, Sacred Flame',
        gratitudeIntro: [
            'Close your eyes and feel the weight of what you’ve released—people, beliefs, versions of yourself.'
        ],
        affirmationIntro: 'Say softly:',
        affirmation: [
            '"Thank you for your fierce love.',
            'For ending what needed ending even when it hurt.',
            'I honour your courage to begin again.',
            'You are not destruction. You are renewal.”'
        ],
        affirmationSettle: 'Let the smoke rise, not in grief—but in blessing.  The fire served its purpose.  You may rest now.',
        reflectionTag: 'What am I ready to release—gently, this time?',
        reflectionSettle: 'Let the flame quiet to an ember.  Feel what still burns true beneath the noise, not to fight, but to become.',
        partingMessage: "The fire has done its work. Let the embers cool and your breath return. The next becoming can wait for the morning.",
    },
    { 
        name: 'Jester',
        slug: 'jester',
        icon: '/archetypes/jester-symbol.png',
        song: '/archetypes/songs/jester.mp3',
        description: "Tells truth through laughter. Masks sorrow in wit. The fool is never foolish, just brave enough to play.",
        tagline: 'find truth in laughter’s echo.',
        base: [
            'You laugh at the rules, not from disrespect, but from seeing how small they are beside the vastness of life.  You dance between moments, turning the ordinary into delight, revealing truths in sideways glances.  People mistake your joy for simplicity, but you know that laughter is a sacred kind of courage.',
            'In your eyes, every mishap is a miracle, every fall a pirouette.  You are the alchemist of lightness, reminding the world it’s safe to exhale.',
        ],
        shadowTag: 'when lightness becomes armour, and laughter hides the ache.',
        shadowList: [
            'You joke to dodge discomfort, even when your heart is breaking.',
            "You’re afraid people won’t take you seriously if they see your depth.",
            'You move quickly from feeling to feeling, fearing stillness might bring pain.',
            "You feel pressure to always uplift others, even when you're the one in need.",
        ],
        reframeTag: "your laughter was never a mask, it was a lantern held in the dark.",
        reframeText: "These aren’t flaws, they’re survival skills, shaped by someone who turned pain into play.  But the Jester isn’t just joy, they’re a truth-teller in disguise.  Your lightness doesn’t need to hide your depth. When you let both live, you become whole and your laughter heals more than you know.",
        gratitudeThanks: 'Thank You, Bright Soul',
        gratitudeIntro: [
            'Place a hand gently over your heart. Feel its rhythm—steady, playful, alive.'
        ],
        affirmationIntro: 'Close your eyes and say softly:',
        affirmation: [
            '"Thank you for finding light in the dark.',
            'Thank you for helping me laugh when I thought I couldn’t.',
            'I see your wisdom now, and I will carry it with care.”'
        ],
        affirmationSettle: 'Let yourself smile—not to hide anything, but as a quiet yes to your own joy.',
        reflectionTag: 'If I no longer had to lift the mood—what might I finally allow myself to feel?',
        reflectionSettle: 'Let the echo of the laughter fade like twilight. What truth remains when the smile softens?',
        partingMessage: "Stumble into joy.  Laugh at the stars on your way home.  When the sky feels heavy, return — we’ll be here.",
    },
    { 
        name: 'Everyman',
        slug: 'friend',
        icon: '/archetypes/everyman-symbol.png',
        song: '/archetypes/songs/friend.mp3',
        description: "Holds space without asking. Arrives without needing. A quiet presence that steadies the storm.",
        tagline: 'let your softness be your strength.',
        base: [
            'You remember the world as it once was—before the noise, before the doubt.  You believe not out of ignorance, but because your soul recognises the good beneath the dust.  Where others see risks, you see beginnings.  Where others falter, you still trust.',
            'To be you is to see with unclouded eyes, not because you haven’t seen pain, but because you still choose to hope.  People are drawn to your lightness, your quiet joy, your refusal to close your heart.  You are the whisper in the storm that says: "It’s safe to try again."',
        ],
        shadowTag: 'when your open heart hides behind clouds of avoidance.',
        shadowList: [
            'You avoid conflict, hoping it will resolve itself if ignored.',
            'You say “I’m fine” even when your heart is aching.',
            'You place trust in people or systems that haven’t earned it.',
            'You feel shame for your sensitivity, as if softness were a flaw.',
        ],
        reframeTag: "your quiet presence was never small, it was the shelter others prayed for.",
        reframeText: 'Your softness is not weakness, it is your superpower in a hardened world.  You do not have to pretend everything is okay to keep your light.  Real innocence isn’t blindness—it’s the brave choice to keep loving after being hurt.  And that, dear one, is strength.',
        gratitudeThanks: 'Thank You, Gentle One',
        gratitudeIntro: [
            'Sit somewhere quiet—where sunlight can reach you, or a breeze can be felt.',
        ],
        affirmationIntro: 'Say slowly:',
        affirmation: [
            '“Thank you for keeping my heart soft.',
            'For seeing the beauty others forget to notice,',
            'For teaching me that beginning again is holy work.',
            'I honour the hope that lives inside me.”',
        ],
        affirmationSettle: 'Let yourself smile without needing a reason. Let it be enough to just be.',
        reflectionTag: 'Where in my life can I stop pretending and still remain soft?',
        reflectionSettle: 'Let the stillness hold you like a trusted hand.  You don’t need to reach, you already belong.',
        partingMessage: "Not all beginnings are loud.  This one will wait in the quiet until you’re ready to try again.",
    },
    { 
        name: 'Sage',
        slug: 'sage',
        icon: '/archetypes/sage-symbol.png',
        song: '/archetypes/songs/sage.mp3',
        description: "Doesn’t shout, just listens. Speaks only after seeing. The wisdom was never in the answer — but in the stillness between.",
        tagline: 'light the path that begins inside you.',
        base: [
            "You have always sought what lies beneath the surface. While others chase answers, you ask better questions. Quietly, patiently, you gather light from the corners of things, stitching it into meaning. You speak less — but when you do, the room stills.",
            "Books are your companions, silence your teacher. You are the keeper of insight — the still water that runs deep. People come to you not just for knowledge, but for how you see: with clarity, with compassion, with the long view in mind. You are a lighthouse, not a spotlight.",
        ],
        shadowTag: 'when reflection becomes retreat, and knowing replaces feeling.',
        shadowList: [
            'You find yourself observing instead of participating—always watching, rarely joining.',
            'You withhold your voice, not from humility, but from fear of being misunderstood.',
            'You bury emotions beneath logic, analysing instead of feeling.',
            'You grow weary of people who don’t seek depth, and sometimes judge their noise.',
        ],
        reframeTag: "wisdom was never knowing more — it was needing less to feel whole.",
        reframeText: 'You are not here to have all the answers.  You are here to be present with the questions.  Wisdom doesn’t always mean stepping back, it sometimes means stepping closer.  Let your insight illuminate, not isolate.  You don’t have to hold it all alone.',
        gratitudeThanks: 'Thank You, Quiet Flame',
        gratitudeIntro: [
            'Close your eyes and place your hand over your chest.',
        ],
        affirmationIntro: 'Say softly:',
        affirmation: [
            '“Thank you for teaching me to pause.',
            'For seeing the long arc of things.',
            'For reminding me that truth comes quietly.',
            'And that my presence is enough.',
            'I honour your stillness.”',
        ],
        affirmationSettle: 'Let a deep breath carry that knowing through you.',
        reflectionTag: 'Where might I trade understanding for experience, and feel instead of analysing?',
        reflectionSettle: "Let the thought dissolve like morning mist.  The answer doesn’t need to come, just notice what remains when the noise is gone.",
        partingMessage: "The question will still be here tomorrow. For now, close the book, sip the quiet, and let the night speak to you.",
    },
    { 
        name: 'Nurturer',
        slug: 'healer',
        icon: '/archetypes/nurturer-symbol.png',
        song: '/archetypes/songs/healer.mp3',
        description: "Sees what pain hides.  Tends what others overlook.  Wholeness is found not in fixing, but in honouring the wound.",
        tagline: 'hold the world with quiet care.',
        base: [
            "You are the warm hands that hold others together when they think they might fall apart.  You move through the world gently, stitching kindness into its seams.  You don’t need recognition.  Your reward is in the healing, in the way someone breathes easier after being near you.",
            "Your love is not loud, but it is lasting.  You are the quiet flame that never burns out.  When the world feels too sharp, you soften it.  You make room.  You make safety.  And in doing so, you remind us what love looks like in action.",
          ],          
        shadowTag: 'when your care for others forgets to include yourself.',
        shadowList: [
            'You say yes when you are already running on empty.',
            'You feel guilty when resting, as if love must always be earned.',
            'You hold pain that does not belong to you.',
            "You find it hard to ask for help, even when you're quietly aching."
        ],
        reframeText: "Your kindness is a balm, but even the healer needs healing.  You are not selfish for needing space.  You are not weak for needing rest.  Your love is strongest when it flows through you, not only from you.  Let the tenderness you offer others finally reach your own heart.",
        gratitudeThanks: "Thank You, Steady Flame",
        gratitudeIntro: [
            'Light a candle—or close your eyes and imagine one.',
        ],
        affirmationIntro: 'Say softly:',
        affirmation: [
            '“Thank you for the warmth you give so freely.',
            'For every unseen moment of care.',
            'For the safety you offer with a single look or gesture.',
            'I see you now. I honour your quiet devotion.”',
        ],
        affirmationSettle: 'Let the silence wrap around you like a soft blanket. Let it hold you.',
        reflectionTag: 'Where in my life can I care for myself the way I care for others?',
        reflectionSettle: "Let the question rest like a warm hand over your heart.  You don’t need to solve it.  Just sit beside it, and breathe.",
        partingMessage: "You’ve given so much. Now take this—our quiet blessing for your heart. Let it carry you gently, wherever you go.",
    },
    { 
        name: 'Artist',
        slug: 'artist',
        icon: '/archetypes/artist-symbol.png',
        song: '/archetypes/songs/artist.mp3',
        description: "Shapes what words cannot hold.  Breathes meaning into matter.  Doesn’t chase beauty, but becomes it.",
        tagline: 'shape beauty from what you carry inside.',
        base: [
            "You see what others miss, the fracture in the light, the ache behind a glance, the stories waiting in silence.  Your hands were made to translate the unspoken, to give form to feeling, to turn rawness into beauty.  You don’t create for praise.  You create because not creating feels like forgetting how to breathe.",
            "The world sometimes moves too fast, too loud, but you know how to slip between its moments.  In colour, in texture, in line, you leave traces of soul behind: quiet reminders that the sacred still lives in the cracks.  You are not here to decorate.  You are here to remember.",
          ],          
        shadowTag: 'when expression becomes pressure, and beauty becomes burden.',
        shadowList: [
            "You feel paralysed by perfection, unable to begin unless it’s already flawless in your mind.",
            "You disappear into your inner world and struggle to return, feeling unseen or misunderstood by others.",
            "You compare your creations to others and quietly decide your voice is too strange, too soft, too much.",
            "You carry the ache of creating for others instead of for yourself, yet fear no one will listen if you don’t.",
        ],
        reframeTag: "your gift was never the art, it was the way you feel the world.",
        reframeText: "Your gift is sacred because it is yours.  The world doesn’t need polished brilliance, it longs for sincerity.  Even your unfinished sketches, your whispered verses, your strange little visions... they are maps for someone else’s heart.  You do not need to be understood by everyone.  Only by yourself.",
        gratitudeThanks: "Thank You, Tender Maker",
        gratitudeIntro: [
            "Close your eyes and picture the first time you made something just for the joy of it.",
            "Let that version of you sit beside you now.",
        ],
        affirmationIntro: 'Say gently:',
        affirmation: [
            '“Thank you for seeing what others miss.',
            'Thank you for giving shape to what had none.',
            'You are allowed to make beauty even when no one applauds.',
            'You are enough, even when the page is blank.”',
        ],
        affirmationSettle: "Feel your hands unclench.  Let the silence become your canvas again.",
        reflectionTag: "What do I long to create when no one is watching?",
        reflectionSettle: "Let the question echo like brushstrokes in silence.  You don’t need to paint the answer.  Just feel the colour it leaves behind.",
        partingMessage: "The canvas is never empty. Even now, your soul leaves colour behind. Rest your brushes, and dream in pigment.",
    },
    { 
        name: 'Ruler',
        slug: 'ruler',
        icon: '/archetypes/ruler-symbol.png',
        song: '/archetypes/songs/ruler.mp3',
        description: "Builds where others destroy.  Sets boundaries, not cages.  Power isn’t taken, it’s carried with care.",
        tagline: 'rule not by force, but by presence.',
        base: [
            "You were born with the weight of invisible crowns.  Not the kind forged from gold, but from quiet responsibility, from the ache to bring order where chaos blooms.  You feel the pulse of the world and step forward, not to control, but to tend, to steady, to hold.",
            "Your strength is not loud.  It hums beneath the surface, a patient rhythm of decisions made in silence.  And though no one sees the cost, you bear it still—because something within you knows that peace must be chosen, again and again.",
          ],          
        shadowTag: "when the weight of responsibility hardens the heart that meant only to protect.",
        shadowList: [
            "You feel the need to be in control, even when you're exhausted.",
            "You take on more than is fair, believing if you don’t hold it all, everything will fall apart.",
            "You struggle to trust others with power, fearing they won’t care as deeply as you do.",
            "You quietly resent how rarely others see your sacrifice—and how often they expect more.",
        ],
        reframeTag: "your power was never control — it was the care you gave in holding it.",
        reframeText: "Your desire to lead comes from love, not ego.  You see what must be done, and you step forward when others hesitate.  But even kings must rest.  True sovereignty is not about holding everything together, it’s about knowing what can be shared, and trusting that the world won’t crumble when you lay the crown down for a while.",
        gratitudeThanks: "Thank You, Steady One",
        gratitudeIntro: [
            "Sit with your back straight, feet planted.  Feel the ground holding you.",
        ],
        affirmationIntro: "Breathe deeply, and speak this slowly:",
        affirmation: [
            '“Thank you for carrying what others could not.',
            'Thank you for keeping the peace, even when it cost you.',
            'You have done enough for today. You are allowed to rest.”',
        ],
        affirmationSettle: "Let the silence after these words be your throne.",
        reflectionTag: "What weight have I been carrying that no longer belongs to me?",
        reflectionSettle: "Let the need to hold it all soften.  You don’t have to lead right now.  Just rest in what remains when the crown is set down.",
        partingMessage: "Your kingdom within is still standing. Let the weight fall for now. You’ve already held more than most ever see.",
    },
    { 
        name: 'Magician',
        slug: "magician",
        icon: '/archetypes/magician-symbol.png',
        song: '/archetypes/songs/magician.mp3',
        description: "Moves between what is and what could be.  Weaves wonder through pattern.  When still, the hidden speaks.",
        tagline: "turn what you dream into what you hold.",
        base: [
            "You have always known that reality is not fixed.  You sense the hidden threads, the quiet symbols, the truth behind the curtain.  Transformation is your art.  Where others see problems, you see portals.  Your words are spells, your dreams blueprints.",
            "It can be lonely, holding visions others don’t yet believe in. But you were never here to follow.  You are here to remember, to transmute, to guide others home through unfamiliar paths.  You are the bridge between what is and what could be.  The world changes when you do.",
          ],          
        shadowTag: "when your gift for transformation turns inward, and begins to unravel you.",
        shadowList: [
            "You overthink and spiral into the abstract, losing touch with the present moment.",
            'You retreat into your visions, feeling misunderstood, disconnected, or “too much.”',
            "You manipulate your own truth to protect others or to avoid being fully seen.",
            "You take responsibility for healing everything, forgetting you are human too.",
        ],
        reframeTag: "you were never here to explain the magic — only to feel it move through you.",
        reframeText: "Your mind is a sacred loom, weaving futures from threads others can’t yet see.  But even the weaver must rest.  You don’t have to fix everything.  It is enough to sit with the mystery, to trust that the magic will arrive when it’s ready.  The world doesn’t need your perfection.  It needs your presence.",
        gratitudeThanks: "Thank You, Dream Weaver",
        gratitudeIntro: [
            'Place your hand gently on your chest or forehead, wherever you feel your visions live.',
        ],
        affirmationIntro: 'Say softly:',
        affirmation: [
            '“Thank you for seeing what others cannot.',
            'For the light you’ve carried through shadows.',
            'For the courage to imagine something better.',
            'I honour the magic I bring, even when it’s quiet.”',
        ],
        affirmationSettle: "Breathe slowly and feel your body holding space for possibility, not just for others, but for you.",
        reflectionTag: "Where in my life can I trust the unfolding, instead of shaping it?",
        reflectionSettle: "Let the mind rest.  Let mystery breathe.  What matters will rise — not with force, but in its own time, like mist revealing a hidden path.",
        partingMessage: "The spell is still in motion. Let the unseen keep turning while you rest your eyes. Return when the stars feel close again."
    },
  ];
